'use client';

interface QueryModalProps {
  isOpen: boolean;
  onClose: () => void;
  query: any;
}

export default function QueryModal({ isOpen, onClose, query }: QueryModalProps) {
  if (!isOpen || !query) return null;

  const formattedQuery = JSON.stringify(query, null, 2);

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
      onClick={onClose}
    >
      <div 
        className="bg-white rounded-lg shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 bg-gray-100">
          <div>
            <h2 className="text-2xl font-bold text-wu-black">Generated Query</h2>
            <p className="text-sm text-gray-600 mt-1">
              DynamoDB query generated by the AI
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-600 hover:bg-gray-200 rounded-full p-2 transition-colors"
          >
            <svg
              className="w-6 h-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        {/* Query Content */}
        <div className="flex-1 overflow-auto p-6">
          <pre className="bg-gray-900 text-green-400 p-4 rounded-lg overflow-x-auto text-sm font-mono">
            {formattedQuery}
          </pre>
          
          <div className="mt-4 p-4 bg-blue-50 border-l-4 border-blue-400 rounded">
            <h3 className="font-semibold text-blue-900 mb-2">Query Details:</h3>
            <ul className="text-sm text-blue-800 space-y-1">
              <li><strong>Operation:</strong> {query.operation || 'N/A'}</li>
              <li><strong>Table:</strong> {query.table_name || 'N/A'}</li>
              {query.index_name && <li><strong>Index:</strong> {query.index_name}</li>}
              {query.limit && <li><strong>Limit:</strong> {query.limit}</li>}
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end p-6 border-t border-gray-200 bg-gray-50">
          <button
            onClick={onClose}
            className="px-6 py-2 bg-wu-black text-wu-yellow font-semibold rounded-lg shadow-md hover:shadow-lg transition-all duration-200 hover:scale-105"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
